Models/Tablero.cs
using RehacerTPS.ViewModels;

namespace RehacerTPS.Models;

public class Tablero
{
    private int id;
    private int id_usuario_propietario;
    private string nombre;
    private string? descripcion;

    public Tablero()
    {
    }

    public Tablero(int idTab, int id_us_prop, string? nombre, string? descripcion)
    {
        this.id = idTab;
        this.id_usuario_propietario = id_us_prop;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Tablero(CrearTableroViewModel tabvm)
    {
        id_usuario_propietario = tabvm.id_usuario_asignado;
        nombre = tabvm.nombre;
        descripcion=tabvm.descripcion;
    }
    public Tablero(ModificarTableroViewModel tabvm){
        id=tabvm.id;
        id_usuario_propietario=tabvm.id_usuario_asignado;
        nombre=tabvm.nombre;
        descripcion=tabvm.descripcion;
    }

    public int Id { get => id; set => id = value; }
    public int Id_usuario_propietario { get => id_usuario_propietario; set => id_usuario_propietario = value; }
    public string Nombre { get => nombre; set => nombre = value; }
    public string? Descripcion { get => descripcion; set => descripcion = value; }
}

Controllers/TableroController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RehacerTPS.Models;
using RehacerTPS.Repository;
using RehacerTPS.ViewModels;

namespace RehacerTPS.Controllers;

public class TableroController : Controller
{
    private readonly ILogger<TableroController> _logger;
    private readonly ITableroRepository _manejoTableros;
    private readonly IUsuarioRepository _manejoUsuarios;
    private readonly ITareaRepository _manejotareas;

    public TableroController(ILogger<TableroController> logger, ITableroRepository manejoTableros, IUsuarioRepository manejoUsuarios,ITareaRepository manejotareas)
    {
        _logger = logger;
        this._manejoTableros = manejoTableros;
        this._manejoUsuarios = manejoUsuarios;
        this._manejotareas = manejotareas;
    }
    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var tableros = _manejoTableros.ListarTableros();
            var usuarios = _manejoUsuarios.ListarUsuarios();
            return View(new IndexTablerosViewModel(tableros, usuarios, PermisoAdmin(),(int)IdUsuarioLogueado()));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }

   

    [HttpGet]
    public IActionResult Crear()
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            return View(new CrearTableroViewModel((int)IdUsuarioLogueado()));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult CrearP(CrearTableroViewModel tab)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("No se cargaron de forma correcta los elementos del formulario"));
            _manejoTableros.CrearTablero(new Tablero(tab));
            return RedirectToAction("IndexTablerosUsuario",new {id=IdUsuarioLogueado()});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Modificar(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var modificar = _manejoTableros.GetTablero(id);
            var idUsPropietario = _manejoTableros.idUsuarioPropietario(id);
            if(!Permiso((int)idUsPropietario))throw(new Exception("El usuario "+NombreUsuarioLogueado()+" intento modificar el tablero "+modificar.Nombre+" del usuario de id "+idUsPropietario));
            return View(new ModificarTableroViewModel(id, modificar,(int)idUsPropietario));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }

   
    [HttpPost]
    public IActionResult ModificarP(ModificarTableroViewModel tabvm)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("Error al cargar los datos en el formulario"));
            if(!Permiso(tabvm.id_usuario_asignado))throw new Exception("El usuario "+NombreUsuarioLogueado()+" de id "+IdUsuarioLogueado()+" intento modificar un tablero de otro usuario");
            var tablero = new Tablero(tabvm);
            _manejoTableros.ModificarTablero(tabvm.id, tablero);
            return RedirectToAction("IndexTablerosUsuario",new{id=tabvm.id_usuario_asignado});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Eliminar(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var idUs = _manejoTableros.idUsuarioPropietario(id);
            if(!Permiso((int)idUs))throw new Exception("El usuario de id "+IdUsuarioLogueado()+" intento eliminar un tablero de otro usuario");
            int cantTareasEliminadas = _manejotareas.EliminarTareasTablero(id);
            _logger.LogInformation("Se eliminaron "+cantTareasEliminadas+" del tablero de id "+id);
            _manejoTableros.EliminarTablero(id);
            return RedirectToAction("IndexTablerosUsuario",new{id=idUs});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult IndexTablerosUsuario(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            var tableros = _manejoTableros.ListarTablerosUsuario(id);
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var nombreUsuario = _manejoUsuarios.GetNombreUsuario(id);
            var permisoAsignar = Permiso(id);
            return (View(new IndexTablerosUsuarioViewModel(tableros, usuarios,nombreUsuario,permisoAsignar,(int)IdUsuarioLogueado())));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    //FUNCIONES PRIVADAS
    private int? IdUsuarioLogueado()
    {
        return HttpContext.Session.GetInt32("Id");
    }
     private bool NoSeLogueoElUsuario()
    {
        return !HttpContext.Session.IsAvailable || NombreUsuarioLogueado() == null;
    }

    private string? NombreUsuarioLogueado()
    {
        return HttpContext.Session.GetString("Nombre");
    }
    private string? RolUsuarioLogueado(){
        return HttpContext.Session.GetString("Rol");
    }
    private bool Permiso(int id){
        return (IdUsuarioLogueado()==id || RolUsuarioLogueado()=="Administrador");
    } 
    private bool PermisoAdmin(){
        return (RolUsuarioLogueado()==Rol.Administrador.ToString());
    }
}

Controllers/TareaController.cs
using System.Diagnostics;
using System.Runtime.Versioning;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.Mvc;
using RehacerTPS.Models;
using RehacerTPS.Repository;
using RehacerTPS.ViewModels;

namespace RehacerTPS.Controllers;

public class TareaController : Controller
{
    private readonly ILogger<TareaController> _logger;
    private readonly ITareaRepository _manejoTareas;
    private readonly ITableroRepository _manejoTableros;
    private readonly IUsuarioRepository _manejoUsuarios;

    public TareaController(ILogger<TareaController> logger, ITareaRepository manejoTareas, ITableroRepository manejoTableros, IUsuarioRepository manejoUsuarios)
    {
        _logger = logger;
        this._manejoTareas = manejoTareas;
        this._manejoTableros = manejoTableros;
        this._manejoUsuarios = manejoUsuarios;
    }
    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var tareas = _manejoTareas.Listar();
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var tableros = _manejoTableros.ListarTableros();
            return (View(new IndexTareaViewModel(tareas, usuarios, tableros,PermisoAdmin(),(int)IdUsuarioLogueado())));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }



    [HttpGet]
    public IActionResult Crear()
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var tableros = _manejoTableros.ListarTablerosUsuario((int)IdUsuarioLogueado());
            return View(new CrearTareaViewModel(usuarios, tableros));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult CrearP(CrearTareaViewModel tarVm)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("Error al cargar los datos del formulario"));
            var tarea = new Tarea(tarVm);
            _manejoTareas.CrearTarea(tarea);
            return RedirectToAction("ListarTareasTablero", new { idTablero = tarea.Id_tablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Modificar(int id)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var idUs = _manejoTareas.GetIdUsuarioAsignado(id);
            var permiso = Permiso((int)idUs);
            if (!permiso) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " intentó modificar una tarea de otro usuario"));
            var tareaModificar = _manejoTareas.GetTarea(id);
            var usuarios = _manejoUsuarios.ListarUsuarios();
            List<Tablero> tableros = new List<Tablero>();
            if (PermisoAdmin())
            {
                tableros = _manejoTableros.ListarTableros();
            }
            else
            {
                tableros = _manejoTableros.ListarTablerosUsuario((int)idUs);
            }
            if (RolUsuarioLogueado() == "Administrador")
            {
                return View(new ModificarTareaViewModel(tareaModificar, usuarios, tableros, permiso));
            }
            else
            {
                return RedirectToAction("CambiarEstadoTarea", new { idTar = id });
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult CambiarEstadoTarea(int idTar)
    {
        return View(new CambiarEstadoTareaViewModel(idTar));
    }
    [HttpPost]
    public IActionResult CambiarEstadoTareaP(CambiarEstadoTareaViewModel vm)
    {
        try
        {
            if (NoSeLogueoUsuario()) return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            if (!ModelState.IsValid) throw new Exception("Se enviaron los datos del formulario de forma incorrecta");
            var idUsuarioTarea = _manejoTareas.GetIdUsuarioAsignado(vm.idTarea);
            if (!Permiso((int)idUsuarioTarea)) throw (new Exception($"El usuario {NombreUsuarioLogueado()} intentó acceder a una tarea del usuario de id {idUsuarioTarea}"));
            _manejoTareas.CambiarEstadoTarea(vm.idTarea, vm.nuevoEstado);
            var idTab = _manejoTareas.IdTableroPropietario(vm.idTarea);
            return RedirectToAction("ListarTareasTablero", new { idTablero = idTab });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult ModificarP(ModificarTareaViewModel tar)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("Error al cargar datos del formulario"));
            var permiso = Permiso((int)_manejoTareas.GetIdUsuarioAsignado(tar.id));
            if (!permiso) throw (new Exception("El usuario de id " + IdUsuarioLogueado() + " intentó modificar una tarea de otro usuario"));
            var tarea = new Tarea(tar);
            _manejoTareas.Modificar(tar.id, tarea);
            return RedirectToAction("ListarTareasTablero", new { idTablero = tar.id_tablero });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Eliminar(int id)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var idUs = _manejoTareas.ObtenerIdUsuarioPropietarioDelTableroDeTarea(id);
            if (!Permiso((int)idUs)) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " intentó modificar una tarea del usuario de id " + id));
            var id_tablero = _manejoTareas.IdTableroPropietario(id);
            _manejoTareas.Eliminar(id);
            return RedirectToAction("ListarTareasTablero", new { idTablero = id_tablero });

        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult ListarTareasTablero(int idTablero)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var tareas = _manejoTareas.ListarTareasTablero(idTablero);
            var tablero = _manejoTableros.GetTablero(idTablero);
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var idUsuarioTablero = _manejoTableros.idUsuarioPropietario(idTablero);
            var permisoAdmin = PermisoAdmin();
            var tableros = _manejoTableros.ListarTableros();
            return View(new ListarTareasTableroTareaViewModel(tareas, usuarios, tableros,tablero, tablero.Nombre, (int)IdUsuarioLogueado(), permisoAdmin));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }



    [HttpGet]
    public IActionResult AsignarTareaUsuario(int idTarea)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var idPropietarioTablero = _manejoTareas.ObtenerIdUsuarioPropietarioDelTableroDeTarea(idTarea);
            var permiso = Permiso((int)idPropietarioTablero);
            return (View(new AsignarTareaUsuarioViewModel(idTarea, usuarios, permiso)));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult AsignarTareaUsuarioP(AsignarTareaUsuarioViewModel vm)
    {
        try
        {
            if (NoSeLogueoUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var id_us_prop  = _manejoTareas.ObtenerIdUsuarioPropietarioDelTableroDeTarea(vm.idTarea);
            if (!Permiso((int)id_us_prop)) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " de id " + IdUsuarioLogueado() + "intento acceder a la tarea de id " + vm.idTarea));
            if (!ModelState.IsValid) throw (new Exception("Se cargaron de forma incorrecta los datos en el formulario"));
            _manejoTareas.AsignarTareaUsuario(vm.idTarea, vm.idUsuarioAsignado);
            var idTab = _manejoTareas.IdTableroPropietario(vm.idTarea);
            return RedirectToAction("ListarTareasTablero",new{idTablero =idTab });
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    private bool NoSeLogueoUsuario()
    {
        return !HttpContext.Session.IsAvailable || HttpContext.Session.GetString("Nombre") == null;
    }

    private int? IdUsuarioLogueado()
    {
        return HttpContext.Session.GetInt32("Id");
    }
    private string? NombreUsuarioLogueado()
    {

Views/Tablero/Crear.cshtml
@using RehacerTPS.ViewModels;
@model CrearTableroViewModel;
<h1 class="text-center font-weight-bold">Crear Tablero</h1>
<form asp-asp-controller="Tablero" asp-action="CrearP" method="post">
    <div class="form-group">
        <label for="nombre" asp-for="@Model.nombre"></label>
        <input asp-for="@Model.nombre" class="form-control mb-4" id="nombre" placeholder="tablero de gonzalo Robinson">
        <span asp-validation-for="@Model.nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="desc" asp-for="@Model.descripcion"></label>
        <input asp-for="@Model.descripcion" class="form-control mb-4" id="desc">
        <span asp-validation-for="@Model.descripcion" class="text-danger"></span>
    </div>
@* El id de usuario asignado, no se selecciona, ya que lo asigno desde el controller y será el usuario logueado, esto se debe a que no tiene sentido que un usuario cree tableros de otro usuario*@
<input hidden asp-for="@Model.id_usuario_asignado">
    @* En caso de haber querido que si se pueda hacer lo anterior, cambio por esto. COMENTO ESTA LINEA PORQUE NO TIENE SENTIDO QUE INGRESEE EL USUARIO PROPIETARIO, EN REALIDAD, DEBERIA SER EL USUARIO QUE SE LOGUEÓ *@
    @* <div class="form-group mb-4">
        <label class="form-check-label" for="us">Usuario Propietario</label>
        <select id="us" asp-for="@Model.id_usuario_asignado" class="form-select">
            @foreach (var el in Model.usuarios)
                {
                    <option value="@el.id">@el.nombre</option>
                }
        </select>
        <span asp-validation-for="@Model.id_usuario_asignado" class="text-danger"></span>
    </div> *@
    <div class="btn-group d-flex mt-4">
        <button type="submit" class="btn btn-outline-primary">Crear</button>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Tablero/Index.cshtml
@using RehacerTPS.ViewModels;
@model IndexTablerosViewModel;
<h1 class="text-center font-weight-bold mb-4">Tableros</h1>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col"hidden>Id</th>
            <th scope="col"hidden>Id_Usuario_Propietario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Nombre de Usuario Propietario</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tab in Model.tableros)
        {
            <tr>
                <td hidden>@tab.id></td>
                <td hidden>@tab.id_usuario_asignado></td>
                <td>@tab.nombre</td>
                <td>@tab.descripcion</td>
                <td>@tab.nombreDeUsuario</td>
               <td><a asp-controller="Tarea" asp-action="ListarTareasTablero" asp-route-idTablero="@tab.id"
                        class="btn btn-outline-warning">Listar Tareas</a></td>
                @* Si el usuario tiene permiso de modificar o eliminar, entonces, les muestro los botones para hacerlo sino no *@
                @if (tab.permiso)
                {
                    <td><a asp-controller="Tablero" asp-action="Modificar" asp-route-id="@tab.id"
                            class="btn btn-outline-primary">Modificar</a></td>
                    <td><a asp-controller="Tablero" asp-action="Eliminar" asp-route-id="@tab.id"
                            class="btn btn-outline-danger">Eliminar</a></td>
                }else{
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>
<div class="btn-group d-flex mx-auto">
    <a asp-controller="Tablero" asp-action="Crear" class="btn btn-success align-middle">Crear Tablero</a>
</div>

Views/Tablero/IndexTablerosUsuario.cshtml
@using RehacerTPS.ViewModels;
@model IndexTablerosUsuarioViewModel;
<h1 class="text-center font-weight-bold mb-4">Tableros del usuario @Model.nombreUsuario</h1>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col" hidden>Id</th>
            <th scope="col" hidden>Id_Usuario_Propietario</th>
            <th scope="col">Nombre</th>
            <th scope="col">Descripcion</th>
            <th scope="col">Nombre de Usuario Propietario</th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var tab in Model.tableros)
        {
            <tr>
                <td hidden>@tab.id></td>
                <td hidden>@tab.id_usuario_asignado></td>
                <td>@tab.nombre</td>
                <td>@tab.descripcion</td>
                <td>@tab.nombreDeUsuario</td>
                <td><a asp-controller="Tarea" asp-action="ListarTareasTablero" asp-route-idTablero="@tab.id"
                        class="btn btn-outline-warning">Listar Tareas</a></td>
                @* Permiso determina si es admin o propietario del tablero. Si lo es, puede eliminar y modificar tablero *@
                @if (Model.permisoAsignar)
                {
                    <td><a asp-controller="Tablero" asp-action="Modificar" asp-route-id="@tab.id"
                            class="btn btn-outline-primary">Modificar</a></td>
                    <td><a asp-controller="Tablero" asp-action="Eliminar" asp-route-id="@tab.id"
                            class="btn btn-outline-danger">Eliminar</a></td>
                }else{
                    <td></td>
                    <td></td>
                }
            </tr>
        }
    </tbody>
</table>
@if (Model.permisoAsignar)
{
    <div class="btn-group d-flex mx-auto">
        <a asp-controller="Tablero" asp-action="Crear" class="btn btn-success align-middle">Crear nuevo Tablero</a>
    </div>
}

Views/Tablero/Modificar.cshtml
@using RehacerTPS.ViewModels;
@model ModificarTableroViewModel;
<h1 class="text-center font-weight-bold">Modificar</h1>
<form asp-asp-controller="Tablero" asp-action="ModificarP" method="post">
    <input hidden asp-for="@Model.id">
    <input hidden asp-for="@Model.id_usuario_asignado">
    <div class="form-group">
        <label for="nombre_t" asp-for="@Model.nombre"></label>
        <input asp-for="@Model.nombre" class="form-control mb-4" id="nombre_t" value="@Model.nombre">
        <span asp-validation-for="@Model.nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="desc" asp-for="@Model.descripcion"></label>
        <input asp-for="@Model.descripcion" class="form-control mb-4" id="desc">
        <span asp-validation-for="@Model.descripcion" class="text-danger"></span>
    </div>

    @* COMENTO ESTA LINEA PORQUE NO DEBERIA IR SEGUN LO QUE ENTIENDO, YA QUE EL USUARIO PROPIETARIO DEL TABLERO NO SE DEBE PODER MODIFICAR *@
    @* <div class="form-group mb-4">
        <label class="form-check-label" for="rolUs">Usuario Asignado</label>
        <select id="rolUs" asp-for="@Model.id_usuario_asignado" class="form-select">
            @foreach (var us in Model.usuarios)
            {
                <option value="@us.idUsuario">@us.nombreUsuario</option>

            }
        </select>
        <span asp-validation-for="@Model.id_usuario_asignado" class="text-danger"></span>
    </div> *@
    <div class="btn-group d-flex mt-4">
        <button type="submit" class="btn btn-success">Modificar</button>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}