Models/Usuario.cs
using System;
using RehacerTPS.ViewModels;
namespace RehacerTPS.Models;
public enum Rol{
    Administrador=1,
    Operativo=2
}
public class Usuario{
     private int id;
     private string nombre_de_usuario;
     private string contrasenia;
     private Rol rol;

    public Usuario()
    {
    }

    public Usuario(CrearUsuarioViewModel usuario)
    {
        this.nombre_de_usuario=usuario.nombre_de_usuario;
        contrasenia=usuario.contrasenia;
        rol=usuario.rol;
    }

    public Usuario(ModificarUsuarioViewModel us)
    {
       id = us.id;
       nombre_de_usuario = us.nombre_de_usuario;
       contrasenia = us.contrasenia;
       rol = us.rol;
    }

    public Usuario(int idUs, string nombre_de_usuario, Rol rol, string contrasenia)
    {
        this.id = idUs;
        this.nombre_de_usuario = nombre_de_usuario;
        this.rol = rol;
        this.contrasenia = contrasenia;
    }

    public int Id { get => id; set => id = value; }
    public string Nombre_de_usuario { get => nombre_de_usuario; set => nombre_de_usuario = value; }
    public Rol Rol { get => rol; set => rol = value; }
    public string Contrasenia { get => contrasenia; set => contrasenia = value; }
}

Controllers/TableroController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RehacerTPS.Models;
using RehacerTPS.Repository;
using RehacerTPS.ViewModels;

namespace RehacerTPS.Controllers;

public class TableroController : Controller
{
    private readonly ILogger<TableroController> _logger;
    private readonly ITableroRepository _manejoTableros;
    private readonly IUsuarioRepository _manejoUsuarios;
    private readonly ITareaRepository _manejotareas;

    public TableroController(ILogger<TableroController> logger, ITableroRepository manejoTableros, IUsuarioRepository manejoUsuarios,ITareaRepository manejotareas)
    {
        _logger = logger;
        this._manejoTableros = manejoTableros;
        this._manejoUsuarios = manejoUsuarios;
        this._manejotareas = manejotareas;
    }
    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var tableros = _manejoTableros.ListarTableros();
            var usuarios = _manejoUsuarios.ListarUsuarios();
            return View(new IndexTablerosViewModel(tableros, usuarios, PermisoAdmin(),(int)IdUsuarioLogueado()));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }

   

    [HttpGet]
    public IActionResult Crear()
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            return View(new CrearTableroViewModel((int)IdUsuarioLogueado()));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult CrearP(CrearTableroViewModel tab)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("No se cargaron de forma correcta los elementos del formulario"));
            _manejoTableros.CrearTablero(new Tablero(tab));
            return RedirectToAction("IndexTablerosUsuario",new {id=IdUsuarioLogueado()});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Modificar(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var modificar = _manejoTableros.GetTablero(id);
            var idUsPropietario = _manejoTableros.idUsuarioPropietario(id);
            if(!Permiso((int)idUsPropietario))throw(new Exception("El usuario "+NombreUsuarioLogueado()+" intento modificar el tablero "+modificar.Nombre+" del usuario de id "+idUsPropietario));
            return View(new ModificarTableroViewModel(id, modificar,(int)idUsPropietario));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }

   
    [HttpPost]
    public IActionResult ModificarP(ModificarTableroViewModel tabvm)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw (new Exception("Error al cargar los datos en el formulario"));
            if(!Permiso(tabvm.id_usuario_asignado))throw new Exception("El usuario "+NombreUsuarioLogueado()+" de id "+IdUsuarioLogueado()+" intento modificar un tablero de otro usuario");
            var tablero = new Tablero(tabvm);
            _manejoTableros.ModificarTablero(tabvm.id, tablero);
            return RedirectToAction("IndexTablerosUsuario",new{id=tabvm.id_usuario_asignado});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Eliminar(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var idUs = _manejoTableros.idUsuarioPropietario(id);
            if(!Permiso((int)idUs))throw new Exception("El usuario de id "+IdUsuarioLogueado()+" intento eliminar un tablero de otro usuario");
            int cantTareasEliminadas = _manejotareas.EliminarTareasTablero(id);
            _logger.LogInformation("Se eliminaron "+cantTareasEliminadas+" del tablero de id "+id);
            _manejoTableros.EliminarTablero(id);
            return RedirectToAction("IndexTablerosUsuario",new{id=idUs});
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult IndexTablerosUsuario(int id)
    {
        try
        {
            if (NoSeLogueoElUsuario()) return RedirectToRoute(new { Controller = "Login", Action = "Index" });
            var tableros = _manejoTableros.ListarTablerosUsuario(id);
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var nombreUsuario = _manejoUsuarios.GetNombreUsuario(id);
            var permisoAsignar = Permiso(id);
            return (View(new IndexTablerosUsuarioViewModel(tableros, usuarios,nombreUsuario,permisoAsignar,(int)IdUsuarioLogueado())));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    //FUNCIONES PRIVADAS
    private int? IdUsuarioLogueado()
    {
        return HttpContext.Session.GetInt32("Id");
    }
     private bool NoSeLogueoElUsuario()
    {
        return !HttpContext.Session.IsAvailable || NombreUsuarioLogueado() == null;
    }

    private string? NombreUsuarioLogueado()
    {
        return HttpContext.Session.GetString("Nombre");
    }
    private string? RolUsuarioLogueado(){
        return HttpContext.Session.GetString("Rol");
    }
    private bool Permiso(int id){
        return (IdUsuarioLogueado()==id || RolUsuarioLogueado()=="Administrador");
    } 
    private bool PermisoAdmin(){
        return (RolUsuarioLogueado()==Rol.Administrador.ToString());
    }
}

Controllers/UsuarioController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using RehacerTPS.Models;
using RehacerTPS.Repository;
using RehacerTPS.ViewModels;
namespace RehacerTPS.Controllers;

public class UsuarioController : Controller
{
    private readonly ILogger<UsuarioController> _logger;
    private readonly IUsuarioRepository _manejoUsuarios;
    private readonly ITableroRepository _manejoTableros;
    private readonly ITareaRepository _manejoTareas;

    public UsuarioController(ILogger<UsuarioController> logger, IUsuarioRepository manejoUsuarios, ITableroRepository manejoTableros, ITareaRepository manejoTareas)
    {
        _logger = logger;
        this._manejoUsuarios = manejoUsuarios;
        this._manejoTableros = manejoTableros;
        this._manejoTareas = manejoTareas;
    }
    [HttpGet]
    public IActionResult Index()
    {
        try
        {
            if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            var usuarios = _manejoUsuarios.ListarUsuarios();
            var permiso = PermisoAdmin();
            return View(new IndexUsuarioViewModel(usuarios, permiso, (int)IdUsuarioLogueado()));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Crear()
    {
        if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
        return View(new CrearUsuarioViewModel());
    }
    [HttpPost]
    public IActionResult CrearP(CrearUsuarioViewModel usuario)
    {
        try
        {
            if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid)
            {
                _logger.LogError("Datos no ingresados no válidos.");
                return RedirectToAction("Crear");
            }
            var creado = new Usuario(usuario);
            _manejoUsuarios.CrearUsuario(creado);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }



    [HttpGet]
    public IActionResult Modificar(int id)
    {
        try
        {
            if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!PermisoModEliminar(id)) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " intentó modificar una tarea de otro usuario (de id " + id + ")"));
            var usuario = _manejoUsuarios.GetUsuarioPorId(id);
            return View(new ModificarUsuarioViewModel(usuario));
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpPost]
    public IActionResult ModificarP(ModificarUsuarioViewModel us)
    {
        try
        {
            if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!ModelState.IsValid) throw new Exception("Error al cargar datos del formulario");
            if (!PermisoModEliminar(us.id)) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " intentó modificar una tarea de otro usuario (de id " + us.id + ")"));
            var modificar = new Usuario(us);
            var modificado = _manejoUsuarios.ModificarUsuario(us.id, modificar);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [HttpGet]
    public IActionResult Eliminar(int id)
    {
        try
        {
            if (NoEstaLogueado()) return (RedirectToRoute(new { Controller = "Login", Action = "Index" }));
            if (!PermisoModEliminar(id)) throw (new Exception("El usuario " + NombreUsuarioLogueado() + " intentó eliminar una tarea de otro usuario (de id " + id + ")"));
            //BORRADO EN CASCADA
            int cantTarEliminadas = _manejoTareas.EliminarTareasTablerosDeUsuario(id);
            _logger.LogInformation("Se eliminaron " + cantTarEliminadas + "tareas del usuario de id " + id);
            int cantTablerosEliminados = _manejoTableros.EliminarTablerosUsuario(id);
            _logger.LogInformation("Se eliminaron " + cantTablerosEliminados + "tableros del Usuario de id " + id);
            var eliminado = _manejoUsuarios.EliminarUsuario(id);
            _logger.LogInformation("Se elimino el usuario de id " + id);
            return RedirectToAction("Index");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex.Message);
            return BadRequest();
        }
    }
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    //Para que el código esté más claro
    //FUNCIONES PRIVADAS
    private bool NoEstaLogueado()
    {
        return !HttpContext.Session.IsAvailable || HttpContext.Session.GetString("Nombre") == null;
    }
    private int? IdUsuarioLogueado()
    {
        return HttpContext.Session.GetInt32("Id");
    }
    private string? NombreUsuarioLogueado()
    {
        return HttpContext.Session.GetString("Nombre");
    }
    private string? RolUsuarioLogueado()
    {
        return HttpContext.Session.GetString("Rol");
    }
    private bool PermisoAdmin()
    {
        return (RolUsuarioLogueado() == "Administrador");
    }
    private bool PermisoModEliminar(int id)
    {
        return (PermisoAdmin() || IdUsuarioLogueado() == id);
    }
}

Views/Usuario/Crear.cshtml
@using RehacerTPS.ViewModels;
@model CrearUsuarioViewModel;
<h1 class="text-center font-weight-bold">Crear</h1>
<form asp-asp-controller="Usuario" asp-action="CrearP" method="post">
    <div class="form-group mb-4">
        <label for="nombre_us" asp-for="@Model.nombre_de_usuario"></label>
        <input asp-for="@Model.nombre_de_usuario" class="form-control mb-4" id="nombre_us"
            placeholder="gonzaloRobinson">
        <span asp-validation-for="@Model.nombre_de_usuario" class="text-danger"></span>
    </div>
    <div class="form-group mb-4">
        <label for="pass" asp-for="@Model.contrasenia"></label>
        <input asp-for="@Model.contrasenia" type="password" class="form-control mb-4" id="pass">
        <span asp-validation-for="@Model.contrasenia" class="text-danger"></span>
    </div>
    <div class="form-group mb-4">
        <label class="form-check-label" for="rolUs" asp-for="@Model.rol"></label>
        <select name="rol" id="rolUs" asp-for="@Model.rol" class="form-select">
            <option value="@Rol.Administrador">Administrador</option>
            <option value="@Rol.Operativo">Operativo</option>
        </select>
        <span asp-validation-for="@Model.rol" class="text-danger"></span>
    </div>
    <div class="btn-group d-flex mt-4">
        <button type="submit" class="btn btn-outline-primary">Crear</button>
    </div>
</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Usuario/Modificar.cshtml
@using RehacerTPS.ViewModels;
@model ModificarUsuarioViewModel;
<h1 class="text-center font-weight-bold">Modificar</h1>
<form asp-asp-controller="Usuario" asp-action="ModificarP" method="post">
    <input hidden asp-for="@Model.id">
    <div class="form-group">
        <label for="nombre_us" asp-for="@Model.nombre_de_usuario"></label>
        <input asp-for="@Model.nombre_de_usuario" class="form-control mb-4" id="nombre_us"
            value="@Model.nombre_de_usuario">
        <span asp-validation-for="@Model.nombre_de_usuario" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="pass" asp-for="@Model.contrasenia"></label>
        <input asp-for="@Model.contrasenia" type="password" class="form-control mb-4" id="pass"
            value="@Model.contrasenia">
        <span asp-validation-for="@Model.contrasenia" class="text-danger"></span>
    </div>
    <div class="form-group mb-4">
        <label class="form-check-label" asp-for="@Model.rol" for="rolUs"></label>
        <select name="rol" id="rolUs" asp-for="@Model.rol" class="form-select">
            @if (Model.rol == Rol.Administrador)
            {
                <option value="@Rol.Administrador" selected>Administrador</option>
                <option value="@Rol.Operativo">Operativo</option>
            }
            else
            {
                <option value="@Rol.Administrador" selected>Administrador</option>
                <option value="@Rol.Operativo" selected>Operativo</option>
            }
        </select>
        <span asp-validation-for="@Model.rol" class="text-danger"></span>
    </div>
    <div class="btn-group d-flex mt-4">
        <button type="submit" class="btn btn-success">Modificar</button>
    </div>

</form>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Views/Usuario/index.cshtml
@using RehacerTPS.ViewModels;
@model IndexUsuarioViewModel;
<h1 class="text-center font-weight-bold mb-4">Listar Usuarios</h1>
<table class="table table-dark">
    <thead>
        <tr>
            <th scope="col" hidden></th>
            <th scope="col">Nombre de Usuario</th>
            <th scope="col">Rol</th>
            <th scope="col"></th>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var us in Model.usuarios)
        {
            <tr>
                <td hidden>@us.id></td>
                <td>@us.nombre_de_usuario</td>
                <td>@us.rol.ToString()</td>
                @if (us.id == Model.idUsuarioLogueado || Model.permiso)
                {
                    <td><a asp-controller="Usuario" asp-action="Modificar" asp-route-id="@us.id"
                            class="btn btn-outline-primary">Modificar</a></td>
                    <td><a asp-controller="Usuario" asp-action="Eliminar" asp-route-id="@us.id"
                            class="btn btn-outline-danger">Eliminar</a></td>
                }else{
                    <td></td>
                    <td></td>
                }
                <td><a asp-controller="Tablero" asp-action="IndexTablerosUsuario" asp-route-id="@us.id"
                        class="btn btn-outline-info">Ver Tableros</a></td>
            </tr>
        }
    </tbody>
</table>
<div class="btn-group d-flex mx-auto">
    <a asp-controller="Usuario" asp-action="Crear" class="btn btn-success align-middle">Crear Usuario</a>
</div>